### PR TITLE
Implement "imprimir" in credit profile

### PR DESCRIPTION
**Pull request by novadeveloper14**

### CODE REVIEW

**Review by LinconOssa — APPROVED** [review]
It meets the requirements, it seems to me to be the most appropriate library to use.

**Review by carin91 — CHANGES_REQUESTED** [review]
Refactor to adjust the document to print.
(1) We agreed that you will print it in horizontal orientation.
image

(2) Verify the size of the paper, must meet a standard as letter or A4.
(3) Include margins to guarantee the proper storage of a printed (on paper) document.
(4) I suggest looking for recommendations on the -ux-ui-cruales channel for the printed document, once you attend the requirements bellow.

**Comment by novadeveloper14** [comment]
The requirements were adjusted and the margins were adjusted to storage of a printed (on paper) document.
image

**Review by carin91 — CHANGES_REQUESTED** [review]
Center the credit profile leaving at least 1" (25.4mm) of margin on each side (left-right)
image

**Review by carin91 — APPROVED** [review]

**Pull request merged**
